# Generated by Django 2.0.1 on 2018-01-30 03:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event_rsvp', '0003_auto_20180129_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 31, 3, 50, 32, 149619, tzinfo=utc), verbose_name='End date'),
        ),
    ]
